name: publish_gh_pages

# CHANGEME: If you want to test out changes to this repo without a local setup
# Enable this GitHub Action for the branch you are working on
# This will then push the changes to the `gh-pages` branch on the current repo
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
 push:
    branches: [ test-enabled-preview-gha ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-publish-to-gh-pages:
    env: 
      PROJECT_PATH: "../landscape"
      SKIP_VERSION_CHECK: 1
    # We run only on macos here since the repo2docker tests will run on ubuntu
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out the landscape version in the PR
      uses: actions/checkout@v2
      with:
        repository: 'NREL/mobility_landscape'
        path: 'landscape'

    - name: Check out the most recent version of the landscapeapp
      uses: actions/checkout@v2
      with:
        path: 'landscapeapp'

    - name: Install the landscapeapp dependencies
      run: |
        cd landscapeapp
        npm install yarn
        yarn
    - name: Build and generate previews
      run: |
        cd landscapeapp
        npx yarn build-only
    - name: Publish to the gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./landscape/dist/mobility_landscape
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: ${{ github.event.head_commit.message }}
